export const VERIFY_REGISTER_MAIL_OTP_REQUEST =
  "VERIFY_REGISTER_MAIL_OTP_REQUEST";
export const VERIFY_REGISTER_MAIL_OTP_SUCCESS =
  "VERIFY_REGISTER_MAIL_OTP_SUCCESS";
export const VERIFY_REGISTER_MAIL_OTP_FAILURE =
  "VERIFY_REGISTER_MAIL_OTP_FAILURE";
export const RESET_VERIFY_MAIL_OTP_STATE = "RESET_VERIFY_MAIL_OTP_STATE";
